#-*- coding: utf-8 -*-
COMPANY = [
    'Gameloft',
    'ELECTRONIC ARTS',
    'Warner Bros. International Enterprises',
    'Electronic Arts Inc',
    'Glu',
    'GAMEVIL Inc.',
    'GAMEVIL',
    'MADFINGER Games',
    'Com2uS',
    'Com2uS USA',
    'Ubisoft Entertainment',
    'Halfbrick Studios',
    'The Binary Mill',
    'Defiant Development',
    'SOFTSTAR ENTERTAINMENT INC.',
    'Kiloo',
    'Frima Studio Inc.',
    'Nekki ©',
    'NHN Entertainment Corp.',
    'Future Games of London',
    'Nival',
    'NimbleBit LLC',
    'PIKPOK',
    'G5 Entertainment',
    'SQUARE ENIX Co.,Ltd.',
    'Crescent Moon Games',
    'BANDAI NAMCO Games',
    'Mobigame S.A.R.L.',
    'Supercell',
    'GIGL',
    'King',
    'Chillingo',
    'Pocket Parade',
    'Mooff Games Limited',
    'Kongregate',
    'SNK PLAYMORE',
    'Miniclip.com',
    'Infinite Dreams',
    'Freyr Games',
    'Monstro',
    'SEGA of America',
    'Deemedya',
    'Spry Fox LLC',
    'Angry Mob Games',
    'Shpaga Games',
    'IGG.COM',
    'Triniti Interactive Ltd.',
    'Kairosoft Co.,Ltd',
    'Reliance Big Entertainment (UK) Private Limited',
    'Engage',
    '11 bit studios',
    'Cartoon Network',
    'Disney',
    'Rayark Inc.',
    'Rovio Mobile Ltd.',
    'Rovio Stars Ltd.',
    'Rovio Entertainment Ltd.',
    'Rockstar Games, Inc.',
    'ZeptoLab',
    'Alawar Entertainment, Inc.',
    'Cat Studio HK',
    'Mediocre',
    'Ironhide Game Studio',
    'Activision Publishing, Inc.',
    'SQUARE ENIX Ltd',
    'NEXON M Inc.',
    'PlayStation Mobile Inc.',
    'True Axis',
    'Polarbit',
    'ninja kiwi',
    'Vector Unit',
    'flaregames',
    'Backflip Studios, Inc.',
    'HandyGames',
    'Kabam',
    'EasyTech',
    'The Game Bakers',
    'NaturalMotionGames Ltd',
    '2K Games, Inc.',
    'Bulkypix',
    'One Man Left',
    'Animoca XL',
    'Anuman',
    'Chundos Studio',
    'Craneballs',
    'Moonshark Inc.',
    '1337 & Senri LLC',
    '2D BOY',
    'Big Fish Games',
    'Bithack',
    'Blue Ox Technologies Ltd.',
    'BYRIL',
    'Concrete Software, Inc.',
    'Cube Interactive',
    'Deemedya m.s. ltd.',
    'DeNA Corp.',
    'Doodle Joy Studio',
    'DroidHen',
    'Duolingo',
    'ElectroWolff Games',
    'FDG Entertainment GmbH & Co.KG',
    'Fingersoft',
    'Fire Maple Games',
    'Fox & Sheep',
    'Frozen Gun Games',
    'genina.com',
    'Hemisphere Games',
    'KIMSOONgame',
    'Kiragames Co., Ltd.',
    'KITERETSU inc.',
    'Kiwi, Inc.',
    'Leo De Sol Apps',
    'Marvel Games',
    'MISTWALKER CORPORATION',
    'mixi, Inc.',
    'mobirix',
    'Noodlecake Studios Inc',
    'Outfit7',
    'Pink Pointer',
    'PlayQ Inc',
    'Pocket Gems',
    'RatJar Games',
    'Runaway Studios Inc.',
    'Sanrio Digital',
    'SenseDevil Games',
    'SGN',
    'Silicon Studio',
    'SUD Inc.',
    'Supersolid',
    'TabTale',
    'Telltale Games',
    'TinyCo',
    'TMSOFT',
    'ustwo',
    'Vivid Games S.A.',
    'WeirdBeard'
]